const { app, BrowserWindow, Menu, globalShortcut, clipboard } = require("electron");
const { exec } = require("child_process");
const emoji = require("emojilib");
app.dock.hide();
app.on("ready", () => {
  new BrowserWindow({ show: false });
  const menu = Menu.buildFromTemplate(mappings.map(([from, to]) => ({ label: `${from} · ${to}`, click() {
    clipboard.writeText(to);
    exec(`osascript -e 'tell application "System Events" to keystroke "v" using command down'`);
  }})));
  globalShortcut.register("Control+Option+Command+Space", () => { menu.popup(); });
});

const mappings = [
  ["uparrow", "↑"],
  ["Uparrow", "⇑"],
  ["nearrow", "↗"],
  ["rightarrow", "→"],
  ["->", "→"],
  ["Rightarrow", "⇒"],
  ["=>", "⇒"],
  ["mapsto", "↦"],
  ["|->", "↦"],
  ["leadsto", "↝"],
  ["~>", "↝"],
  ["searrow", "↘"],
  ["downarrow", "↓"],
  ["Downarrow", "⇓"],
  ["swarrow", "↙"],
  ["leftarrow", "←"],
  ["<-", "←"],
  ["<=", "⇐"],
  ["reversemapsto", "↤"],
  ["<-|", "↤"],
  ["nwarrow", "↖"],
  ["updownarrow", "↕"],
  ["Updownarrow", "⇕"],
  ["leftrightarrow", "↔"],
  ["Leftrightarrow", "⇔"],
  ["doublerightarrow", "⇉"],
  ["doubleleftarrow", "⇇"],

  ["alpha", "α"],
  ["beta", "β"],
  ["gamma", "γ"],
  ["Gamma", "Γ"],
  ["delta", "δ"],
  ["Delta", "Δ"],
  ["epsilon", "ϵ"],
  ["varepsilon", "ε"],
  ["zeta", "ζ"],
  ["eta", "η"],
  ["theta", "θ"],
  ["vartheta", "ϑ"],
  ["Theta", "Θ"],
  ["iota", "ι"],
  ["kappa", "κ"],
  ["Kappa", "Κ"],
  ["lambda", "λ"],
  ["Lambda", "Λ"],
  ["mu", "μ"],
  ["nu", "ν"],
  ["xi", "ξ"],
  ["Xi", "Ξ"],
  ["pi", "π"],
  ["varpi", "ϖ"],
  ["Pi", "Π"],
  ["rho", "ρ"],
  ["varrho", "ϱ"],
  ["sigma", "σ"],
  ["varsigma", "ς"],
  ["Sigma", "Σ"],
  ["tau", "τ"],
  ["upsilon", "υ"],
  ["Upsilon", "Υ"],
  ["phi", "φ"],
  ["varphi", "ϕ"],
  ["Phi", "Φ"],
  ["chi", "χ"],
  ["psi", "ψ"],
  ["Psi", "Ψ"],
  ["omega", "ω"],
  ["Omega", "Ω"],

  ["Command", "⌘"],
  ["Option", "⌥"],
  ["Shift", "⇧"],
  ["Control", "⌃"],
  ["Escape", "⎋"],
  ["Backspace", "⌫"],
  ["Delete", "⌦"],
  ["Eject", "⏏"],
  ["Caps Lock", "⇪"],
  ["Tab", "⇥"],
  ["Return", "↩"],
  ["Enter", "⌤"],
  ["Home", "↖"],
  ["End", "↘"],
  ["Page Up", "⇞"],
  ["Page Down", "⇟"],

  ["aleph", "א"],
  ["'", "′"],
  ["prime", "′"],
  ["Prime", "″"],
  ["emptyset", "∅"],
  ["nabla", "∇"],
  ["surd", "√"],
  ["neg", "¬"],
  ["triangleup", "△"],
  ["forall", "∀"],
  ["exists", "∃"],
  ["infty", "∞"],
  ["infinity", "∞"],
  ["circ", "∘"],
  ["+-", "±"],
  ["pm", "±"],
  ["cap", "∩"],
  ["diamond", "◇"],
  ["oplus", "⊕"],
  ["-+", "∓"],
  ["mp", "∓"],
  ["cup", "∪"],
  ["triangleup", "△"],
  ["bigtriangleup", "△"],
  ["ominus", "⊖"],
  ["times", "×"],
  ["uplus", "⊎"],
  ["triangledown", "▽"],
  ["bigtriangledown", "▽"],
  ["otimes", "⊗"],
  ["div", "÷"],
  ["sqcap", "⊓"],
  ["triangleright", "▹"],
  ["oslash", "⊘"],
  ["ast", "∗"],
  ["sqcup", "⊔"],
  ["vee", "∨"],
  ["lor", "∨"],
  ["wedge", "∧"],
  ["land", "∧"],
  ["triangleleft", "◃"],
  ["odot", "⊙"],
  ["wr", "≀"],
  ["amalg", "⨿"],
  ["leq", "≤"],
  ["geq", "≥"],
  ["equiv", "≡"],
  ["|=", "⊨"],
  ["models", "⊨"],
  ["prec", "≺"],
  ["succ", "≻"],
  ["precdot", "⋖"],
  ["succdot", "⋗"],
  ["sim", "∼"],
  ["perp", "⊥"],
  ["bot", "⊥"],
  ["top", "⊤"],
  ["preceq", "≼"],
  ["succeq", "≽"],
  ["simeq", "≃"],
  ["ll", "≪"],
  ["gg", "≫"],
  ["asymp", "≍"],
  ["||", "∥"],
  ["parallel", "∥"],
  ["subset", "⊂"],
  ["supset", "⊃"],
  ["approx", "≈"],
  ["bowtie", "⋈"],
  ["halfbowtieleft", "⋉"],
  ["halfbowtieright", "⋊"],
  ["subseteq", "⊆"],
  ["supseteq", "⊇"],
  ["cong", "≅"],
  ["reversecong", "≌"],
  ["sqsubsetb", "⊏"],
  ["sqsupsetb", "⊐"],
  ["neq", "≠"],
  ["smile", "⌣"],
  ["sqsubseteq", "⊑"],
  ["sqsupseteq", "⊒"],
  ["doteq", "≐"],
  ["frown", "⌢"],
  ["in", "∈"],
  ["ni", "∋"],
  ["notin", "∉"],
  ["propto", "∝"],
  ["vdash", "⊢"],
  ["dashv", "⊣"],
  [".", "·"],
  ["cdot", "·"],
  ["sum", "∑"],
  ["prod", "∏"],
  ["coprod", "∐"],
  ["int", "∫"],
  ["oint", "∮"],
  ["sqrt", "√"],
  ["l", "ł"],
  ["(|", "◖"],
  ["|)", "◗"],
  ["semicircleleft", "◖"],
  ["semicircleright", "◗"],
  ["$`", "≁"],
  ["nottilde", "≁"],
  ["ell", "ℓ"],
  ["N", "ℕ"],
  ["R", "ℝ"],
  ["Z", "ℤ"],
  ["P", "ℙ"],
  ["{", "⌈"],
  ["leftceiling", "⌈"],
  ["}", "⌉"],
  ["rightceiling", "⌉"],
  ["[", "⌊"],
  ["leftfloor", "⌊"],
  ["]", "⌋"],
  ["rightfloor", "⌋"],
  ["minus", "−"],
  ["endofproof", "∎"],
  ["space", "␣"],
  ["therefore", "∴"],
  ["because", "∵"],
  ["brokenbar", "¦"],
  ["ring", "∘"],

  ["star", "★"],
  ["bullet", "•"],
  ["whitebullet", "◦"],
  ["triangularbullet", "‣"],
  ["pointing", "☞"],
  ["dagger", "†"],
  ["ddagger", "‡"],
  ["vdots", "⋮"],
  ["ddots", "⋱"],
  ["cdots", "⋯"],
  ["hdots", "⋯"],
  ["langle", "⟨"],
  ["rangle", "⟩"],
  ["ballotbox", "☐"],
  ["ballotcheck", "☑"],
  ["ballotmark", "☒"],
  ["check", "✓"],
  ["mark", "✗"],
  ["heavycheck", "✔"],
  ["heavymark", "✘"],
  ["S", "§"],
  ["section", "§"],
  ["paragraph", "¶"],
  ["P", "¶"],
  ["reference", "※"],
  ["hyphen", "‐"],
  ["nonbreakinghyphen", "‑"],
  ["endash", "–"],
  ["emdash", "—"],
  ["softhyphen", "­"],
  ["hyphenationpoint", "‧"],
  ["nobreakspace", " "],
  ["enspace", " "],
  ["emspace", " "],
  ["mediumspace", " "],
  ["figurespace", " "],
  ["thinspace", " "],
  ["hairspace", " "],
  ["zerowidthspace", "​"],
  ["zerowidthnonjoiner", "‌"],
  ["zerowidthjoiner", "‍"],
  ["wordjoiner", "⁠"],
  ["ditto", "〃"],
  ["typographyheart", "❤"],
  ["palm", "⸙"],
  ["floral", "❦"],
  ["rotatedfloral", "❧"],

  ["^0", "⁰"],
  ["^1", "¹"],
  ["^2", "²"],
  ["^3", "³"],
  ["^4", "⁴"],
  ["^5", "⁵"],
  ["^6", "⁶"],
  ["^7", "⁷"],
  ["^8", "⁸"],
  ["^9", "⁹"],
  ["^+", "⁺"],
  ["^-", "⁻"],
  ["^=", "⁼"],
  ["^(", "⁽"],
  ["^)", "⁾"],
  ["^a", "ᵃ"],
  ["^b", "ᵇ"],
  ["^c", "ᶜ"],
  ["^d", "ᵈ"],
  ["^e", "ᵉ"],
  ["^f", "ᶠ"],
  ["^g", "ᵍ"],
  ["^h", "ʰ"],
  ["^i", "ⁱ"],
  ["^j", "ʲ"],
  ["^k", "ᵏ"],
  ["^l", "ˡ"],
  ["^m", "ᵐ"],
  ["^n", "ⁿ"],
  ["^o", "ᵒ"],
  ["^p", "ᵖ"],
  ["^r", "ʳ"],
  ["^s", "ˢ"],
  ["^t", "ᵗ"],
  ["^u", "ᵘ"],
  ["^v", "ᵛ"],
  ["^w", "ʷ"],
  ["^x", "ˣ"],
  ["^y", "ʸ"],
  ["^z", "ᶻ"],
  ["^A", "ᴬ"],
  ["^B", "ᴮ"],
  ["^D", "ᴰ"],
  ["^E", "ᴱ"],
  ["^G", "ᴳ"],
  ["^H", "ᴴ"],
  ["^I", "ᴵ"],
  ["^J", "ᴶ"],
  ["^K", "ᴷ"],
  ["^L", "ᴸ"],
  ["^M", "ᴹ"],
  ["^N", "ᴺ"],
  ["^O", "ᴼ"],
  ["^P", "ᴾ"],
  ["^R", "ᴿ"],
  ["^T", "ᵀ"],
  ["^U", "ᵁ"],
  ["^V", "ⱽ"],
  ["^W", "ᵂ"],
  ["^alpha", "ᵅ"],
  ["^beta", "ᵝ"],
  ["^gamma", "ᵞ"],
  ["^delta", "ᵟ"],
  ["^theta", "ᶿ"],
  ["^iota", "ᶥ"],
  ["^phi", "ᵠ"],
  ["^xi", "ᵡ"],

  ["_0", "₀"],
  ["_1", "₁"],
  ["_2", "₂"],
  ["_3", "₃"],
  ["_4", "₄"],
  ["_5", "₅"],
  ["_6", "₆"],
  ["_7", "₇"],
  ["_8", "₈"],
  ["_9", "₉"],
  ["_+", "₊"],
  ["_-", "₋"],
  ["_=", "₌"],
  ["_(", "₍"],
  ["_)", "₎"],
  ["_a", "ₐ"],
  ["_e", "ₑ"],
  ["_h", "ₕ"],
  ["_i", "ᵢ"],
  ["_j", "ⱼ"],
  ["_k", "ₖ"],
  ["_l", "ₗ"],
  ["_m", "ₘ"],
  ["_n", "ₙ"],
  ["_o", "ₒ"],
  ["_p", "ₚ"],
  ["_r", "ᵣ"],
  ["_s", "ₛ"],
  ["_t", "ₜ"],
  ["_u", "ᵤ"],
  ["_v", "ᵥ"],
  ["_x", "ₓ"],
  ["_beta", "ᵦ"],
  ["_gamma", "ᵧ"],
  ["_rho", "ᵨ"],
  ["_phi", "ᵩ"],
  ["_xi", "ᵪ"],

  ["Combining Acute", "́"],
  ["Combining Circumflex", "̂"],
  ["Combining Tilde", "̃"],
  ["Combining Grave", "̀"],
  ["Combining Diaeresis", "̈"],

  ["Quarter Note", "♩"],
  ["Eigth Note", "♪"],
  ["Beamed Eigth Notes", "♫"],
  ["Beamed Sixteenth Notes", "♬"],
  ["Flat", "♭"],
  ["Double Flat", "𝄫"],
  ["Natural", "♮"],
  ["Sharp", "♯"],
  ["G Clef", "𝄞"],
  ["F Clef", "𝄢"],

  [":)", "😀"],
  [":P", "😛"],
  [";)", "😉"],
  [":*", "😘"],
  ["S2", "😍"],
  [":(", "☹"],
  ["shrug", "¯\_(ツ)_/¯"],
  ["fliptable", "(╯°□°）╯︵ ┻━┻"],
  ["disapproval", "ಠ_ಠ"],
].concat(emoji.ordered.map(name => [`:${name}:`, emoji.lib[name].char]));
